import Config

config :business_logic,
  confirmation_secret_key: System.get_env("CONFIRMATION_SECRET_KEY") || raise("CONFIRMATION_SECRET_KEY not set")

config :web, Web.Mailer,
  adapter: Swoosh.Adapters.SendGrid,
  api_key: System.get_env("SENDGRID_API_KEY")

config :web, :base_url, System.get_env("BASE_URL")

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :web, Web.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"
